stage('Deploy to Kubernetes') {
    steps {
        withEnv(['KUBECONFIG=/home/jenkins/.kube/config']) {
            sh '''
                kubectl set image deployment/swe645-survey \
                  student-survey=$IMAGE_NAME:$IMAGE_TAG

                kubectl rollout status deployment/swe645-survey
            '''
        }
    }
}
