
// Author: Disha Yadav
// SWE645 Assignment 2 - Jenkins CI/CD Pipeline

pipeline {
    agent {
        label 'swe645-docker'
    }

    stages {
        stage('Verify Docker') {
            steps {
                sh 'docker --version'
                sh 'docker info'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('SWE645_HW1_Disha') {
                    sh 'docker build -t dyadav4/swe645-student-survey:v2 .'
                }
            }
        }
    }
}
